version: '2'
services:
  nginx:
    image: nginx:1.11.8-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volume/certs:/etc/nginx/certs:ro"
    networks:
      - proxy-tier
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volume/templates/nginx-compose-v2.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volume/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
  db:
    image: mysql:latest
    networks:
      - proxy-tier
    volumes:
        - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret-root-pw
  ghost:
    image: number13/ghost-docker
    restart: always
    depends_on:
      - "nginx-gen"
    networks:
      - proxy-tier
    environment:
        BLOG_DOMAIN: https://www.example.com
        MAIL: example@example.com
        DB_HOST: db
        DB_USR: ghost
        DB_NAME: ghost
        DB_PW: secret-pw
        DB_ROOT_PW: secret-root-pw
        PORT: 80
        VIRTUAL_HOST: example.com,example.com
        VIRTUAL_PORT: 80
        VIRTUAL_NETWORK: nginx-proxy
        LETSENCRYPT_HOST: example.com,www.example.com
        LETSENCRYPT_EMAIL: mail@example.com
        MAIL_SERVER: smtp.example.com
        MAIL_LOGIN: noreply@example.com
        MAIL_PASSWORD: secret-mail-pw
    volumes:
      - "~/blogs/ghostblog:/var/www/ghost/content"
volumes:
  db_data:
networks:
  proxy-tier:
    external:
      name: nginx-proxy
